import fs from "fs";
import OpenAI from "openai";
const openai = new OpenAI();

const prompts = [
  "Abstract soft-focus background with pastel blues and purples, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with sunset orange and pink, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with cool greens and aquamarine, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with gold and rose pink, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with coral and mint, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with teal and lavender, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with forest green and sky blue, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with ice blue and silver, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with mocha and cream tones, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with warm amber and peach, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with plum and navy, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with sapphire and blush, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with turquoise and sunflower yellow, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with charcoal and icy blue, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with ocean blue and foam white, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with pale lilac and dusty rose, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with moss green and sand beige, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with butter yellow and pale cyan, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with cherry red and pearl white, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with lavender and periwinkle, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with grape and apricot, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with cobalt and cotton candy pink, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with jade and smoke grey, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with sky teal and blush orange, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with marigold and powder blue, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with bubblegum pink and violet, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with mauve and steel blue, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with lemon yellow and sea green, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with rust and teal, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with burgundy and taupe, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with olive green and pale peach, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with mint green and sky lavender, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with neon coral and dusty pink, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with denim blue and vanilla, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with canary yellow and teal, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with copper and rose, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with cobalt blue and champagne, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with aqua and steel, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with fuchsia and pale blue, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with midnight blue and gold, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with orchid and celeste, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with pastel peach and aqua green, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with electric blue and pink, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with dusty blue and mauve, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with blush pink and pistachio, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with deep purple and opal, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with soft green and ivory, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with salmon pink and navy, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with pale coral and teal grey, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with arctic blue and magenta haze, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with vanilla and light bronze, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with sky blue and coral rose, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with sage green and copper rose, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with indigo and creamy white, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with apricot and aqua mist, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with blush orange and frosty blue, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with stormy grey and buttercream, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with beige and crimson, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with emerald and pale violet, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with lime and snow white, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with carnation pink and seafoam, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with orchid pink and lemon chiffon, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with pastel green and cotton blue, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with lavender blush and sunset gold, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with berry and icy lavender, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with deep blue and silver mist, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with burnt orange and mint green, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with rose gold and moonlight white, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with plum wine and dusk blue, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with mocha latte and icy mint, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with periwinkle and antique gold, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with mulberry and almond cream, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with papaya and baby blue, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with dusty mauve and snow grey, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with bright citrus and cool teal, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with candy floss pink and turquoise, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with ice mint and sunrise orange, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with shimmer gold and faded teal, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with light moss and glacier blue, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with chocolate brown and beige pink, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with faded lavender and icy lemon, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with denim and washed rose, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with buttermilk and cloud blue, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with desert sand and dusty lilac, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with citrus yellow and ocean green, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with lilac grey and sea mist, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with jade green and burnt peach, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with cloud white and rose beige, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with sorbet orange and plum, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with peach nectar and lagoon blue, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with ash grey and powder violet, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with neon pink and pale cyan, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with grapefruit and sea salt, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with blush peach and celadon, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with lemon cream and arctic teal, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with warm nude and muted jade, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with rose taupe and cool sky, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with frosted plum and lake blue, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with warm terracotta and misty green, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
  "Abstract soft-focus background with powder pink and light olive, smooth gradients, dreamy blur, minimal texture, ideal for blog post cover image",
];

let i = 0;
for (const prompt of prompts) {
  i++;
  const result = await openai.images.generate({
    model: "gpt-image-1",
    prompt,
    quality: "low",
    size: "1536x1024",
  });

  const image_base64 = result.data[0].b64_json;
  const image_bytes = Buffer.from(image_base64, "base64");
  fs.writeFileSync(`images/${i}.png`, image_bytes);
}
